name: todo_list_app
description: A simple todo list application

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.6
  path: ^1.8.2
  sqflite_common_ffi: ^2.3.4+3
  sqflite_common_ffi_web: ^0.4.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true